### ISSUE TITLE
Very basic complaints list (fake data)

### ISSUE THREAD

**Issue by Sgtpluck** [OHS-Hosting-Infrastructure/complaint-tracker#11]
As a PS,
I want to have a landing page with all my complaints
so I can view all my complaints

Acceptance Criteria:
* Navigate to $STAGING-URL 
* Log in to the landing page
You should see a list of complaints that are assigned to your user

Notes:
* This denotes the minimum value add -- so it will not be particularly useful at this stage. This card is just about creating a summary list of complaints.
* we will have to begin with faked data, so this card should include a request to a preferred HSES endpoint that automatically returns an ideal JSON blob. this will help us determine our specific ask to HSES vendors.
* see the design for exact fields to include in the table

**Comment by jduss4** [comment]
Related to #21

**Comment by matt-dobson** [comment]
Related to #20

**Comment by lauranash18f** [comment]
See Figma, Sprint 1 design (let me know if you want an export or Sketch file): https://www.figma.com/file/k8sPnWItmiBAyF4cw6Uuog/OHS-Complaints-Tracker

Sprint 1 design notes:
- Header
  - Display name, followed by role abbreviation (not sure if this is available?)
  - Settings button gives logout and any preference options we develop later.
  - Option to replace name/settings with a single "log out" button is included in the file so that you can skip displaying name if you need to for V1, scroll down to see it
- Sortable table, fields:
  - Issue number:
    - links to the complaint detail
    - use bold for issue number to help highlight any important 
  - Date: absolute date, can discuss ways to improve legibility
    - Time limit: suggest coloring any active issues (new, in progress) that are more than 20 days old yellow, to show that it is coming up on the 30 day limit. If sorting by status, would be at top of the in progress list
  - Status:
    - New: row colored light blue, issue number in bold
    - In Progress
    - Rec. Closure (short for recommend for closure): row colored grey
    - Closed: row colored grey
  - Grantee name: probably will need to be truncated, depending on length — will see with data
  - Issue: drawing on the one line short issue description; will need to be truncated or wrapped — will see with data
  - TTA: TBD/No/Yes options, TBD and No dimmed text with Yes as normal black. Read only for now, assuming action can happen on detail page
  - RAN: TBD/No/Yes options, TBD and No dimmed text with Yes as normal black.  Read only for now, assuming action can happen on detail page

**Comment by lauranash18f** [comment]
Fields matching:
- **Issue Number**: issueId
- **Date**: creationDate
- **Status**: Status
- **Grantee**: grantProgramId (???? presumably can pull grantee from this but unsure)
- **Issue**: issue 
- TTA: does not exist
- RAN: does not exit
